### ISSUE TITLE
Quantity selector is broken on new production

### ISSUE THREAD

**Issue by hundrex** [LucileDT/boustigraille#133] opened 2022-03-10 23:48 UTC
# Scenario
- Go to any recipe page on the production version.
- Click on the quantity selector and choose another value than the default one (4 parts)

# Expected behavior
- Ingredients quantity bellow should be adjusted corresponding to the quantity selected

# Current behavior
- No changes happen.
- The quantity of ingredient shown is also not the one of the default value selected (4) but only of one

**Comment by LucileDT** [comment] 2022-03-11 12:18
Duplicate of #131

**Closed by LucileDT** 2022-03-11 12:18 UTC
Labels: bug
